version = 1

[custom]
enable_rule_generator = true
overwrite_original_rules = true
skip_failed_links = true
#Exclude nodes which remarks match the following patterns. Supports regular expression.
exclude_remarks = [
    "(IPV6|é‡ç½®|æµé‡|ç”¨æˆ·|æœ¬ç«™|æ¼æ´|æ°¸ä¹…è™šé€šè·¯|è½¦|é‚€|å…ç¿»|é‚€è¯·|eevpn|åŸŸå|æœºåœº|åˆ·æ–°|ç¦æ­¢|å¤‡ç”¨ç™»å½•|è®¡åˆ’|é¢æ¿|å¿˜è®°|åˆ°æœŸ|å¥—é¤|å®˜ç½‘|æ›´å¤š|å…³æ³¨|25å€ç‡|http|å¢åŠ |æŒç»­|æ¸ é“|è´­ä¹°|QQ|Ins|äºŒæ‰‹)",
]

[[rulesets]]
group = "ğŸ¯ å›½å†…æµé‡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å›½å†…æµé‡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"

[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list"

[[rulesets]]
group = "ğŸ›¡ï¸ éšç§é˜²æŠ¤"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml"

[[rulesets]]
group = "ğŸ“¢ è°·æ­ŒFCM"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"

[[rulesets]]
group = "ğŸ¯ å›½å†…æµé‡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"

[[rulesets]]
group = "ğŸ¯ å›½å†…æµé‡"
ruleset = "clash-classic:https://raw.githubusercontent.com/Clementine33/Rule/main/Custom/direct.yaml"

[[rulesets]]
group = "ğŸš© ç¤¾äº¤å¹³å°IPå½’å±åœ°"
ruleset = "clash-classic:https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider.yaml"

[[rulesets]]
group = "ğŸ’¬ OpenAi"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml"

[[rulesets]]
group = "ğŸ•¹ï¸ æ¸¸æˆä¸‹è½½"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.yaml"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml"

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"

[[rulesets]]
group = "ğŸ“¹ YouTube"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"

[[rulesets]]
group = "ğŸ¥ Netflix"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"

[[rulesets]]
group = "ğŸ¬ EMBY"
ruleset = "clash-classic:https://raw.githubusercontent.com/Clementine33/Rule/main/Custom/emby.yaml"

[[rulesets]]
group = "ğŸ¬ EMBY"
ruleset = "clash-classic:https://raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/Emby.yaml"

[[rulesets]]
group = "ğŸ¬ EMBY"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.yaml"

[[rulesets]]
group = "ğŸ“º Bilibili"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.yaml"

[[rulesets]]
group = "ğŸ“º Bilibili"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"

[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml"

[[rulesets]]
group = "ğŸµ Spotify"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml"

[[rulesets]]
group = "ğŸµ TikTok"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml"

[[rulesets]]
group = "ğŸ¼ EHGallery"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EHGallery/EHGallery.yaml"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml"

[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml"

# [[rulesets]]
# group = "ğŸš€ å›½å¤–æµé‡"
# ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
[[rulesets]]
group = "ğŸš€ å›½å¤–æµé‡"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.list"

[[rulesets]]
group = "ğŸ¯ å›½å†…æµé‡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å›½å†…æµé‡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "ğŸ¯ å›½å†…æµé‡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

[[rulesets]]
group = "ğŸ¯ å›½å†…æµé‡"
ruleset = "clash-ipcidr:https://cdn.jsdelivr.net/gh/soffchen/GeoIP2-CN@release/clash-rule-provider.yml"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

[[custom_groups]]
name = "ğŸš€ å›½å¤–æµé‡"
type = "select"
rules = [
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨é€‰æ‹©1"
type = "select"
rules = ["[].*"]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"
type = "select"
rules = ["[].*"]

[[custom_groups]]
name = "âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
type = "select"
rules = ["(0\\.\\d)", "((?i)media)"]

# [[custom_groups]]
# name = "âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"
# type = "load-balance"
# url = "http://www.gstatic.com/generate_204"
# interval = 300
# strategy = "consistent-hashing"
# rules = ["(0\.\d)", "((?i)media)"]
[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
    "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—",
]

[[custom_groups]]
name = "ğŸš© ç¤¾äº¤å¹³å°IPå½’å±åœ°"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "(?i)^(?!.*(media)).*(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong).*$",
    "(?i)^(?!.*(media)).*(ğŸ‡¹ğŸ‡¼|å°|TW|Taiwan).*$",
    "(?i)^(?!.*(media)).*(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore).*$",
    "(?i)^(?!.*(media)).*(ğŸ‡ºğŸ‡¸|ç¾|US|United States).*$",
    "(?i)^(?!.*(media)).*(ğŸ‡¯ğŸ‡µ|[^-]æ—¥(?!ç”¨|åˆ©äºš)|JP|Japan).*$",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸ¼ EHGallery"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong)",
    "(ğŸ‡¹ğŸ‡¼|å°|TW|Taiwan)",
    "(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore)",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸµ TikTok"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸ¬ EMBY"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ“¹ YouTube"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
]

[[custom_groups]]
name = "ğŸ¥ Netflix"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
]

[[custom_groups]]
name = "ğŸ“º Bilibili"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "(æ¾³é—¨|MO|ğŸ‡²ğŸ‡´)",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rules = ["[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸµ Spotify"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ å›½å¤–æµé‡",
    "(è²å¾‹å®¾|PH)",
    "(å·´åŸºæ–¯å¦|PK)",
    "(åœŸè€³å…¶|TR|Turkey)",
    "(å°¼æ—¥åˆ©äºš|NG)",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
]

[[custom_groups]]
name = "ğŸ“² Telegram"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
]

[[custom_groups]]
name = "ğŸ’¬ OpenAi"
type = "select"
rules = [
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rules = ["[]ğŸš€ å›½å¤–æµé‡", "[]ğŸ¯ å›½å†…æµé‡", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rules = ["[]ğŸ¯ å›½å†…æµé‡", "[]ğŸš€ å›½å¤–æµé‡", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ“¢ è°·æ­ŒFCM"
type = "select"
rules = ["[]ğŸš€ å›½å¤–æµé‡", "[]ğŸ¯ å›½å†…æµé‡", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rules = ["[]ğŸ¯ å›½å†…æµé‡", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ•¹ï¸ æ¸¸æˆä¸‹è½½"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ¯ å›½å†…æµé‡"
type = "select"
rules = ["[]DIRECT", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rules = ["[]REJECT", "[]DIRECT", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ›¡ï¸ éšç§é˜²æŠ¤"
type = "select"
rules = ["[]REJECT", "[]DIRECT", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
type = "url-test"
rules = ["!!GROUPID=0!!(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "url-test"
rules = ["!!GROUPID=0!!(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹"
type = "url-test"
rules = ["!!GROUPID=0!!(ğŸ‡¹ğŸ‡¼|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "url-test"
rules = [
    "!!GROUPID=0!!(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥(?!ç”¨|åˆ©äºš)|JP|Japan)"
]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rules = [
    "!!GROUPID=0!!(ğŸ‡ºğŸ‡¸|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)",
]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
