[[custom_groups]]
name = "ğŸš€ å›½å¤–æµé‡"
type = "select"
rules = [
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]DIRECT",
]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨é€‰æ‹©1"
type = "select"
rules = ["[].*"]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"
type = "select"
rules = ["[].*"]

[[custom_groups]]
name = "âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
type = "select"
rules = ["(0\\.\\d)", "((?i)media)"]

# [[custom_groups]]
# name = "âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"
# type = "load-balance"
# url = "http://www.gstatic.com/generate_204"
# interval = 300
# strategy = "consistent-hashing"
# rules = ["(0\.\d)", "((?i)media)"]
[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
    "[]âš–ï¸ è´Ÿè½½å‡è¡¡-æ•£åˆ—",
]

[[custom_groups]]
name = "ğŸš© ç¤¾äº¤å¹³å°IPå½’å±åœ°"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "(?i)^(?!.*(media)).*(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong).*$",
    "(?i)^(?!.*(media)).*(ğŸ‡¹ğŸ‡¼|å°|TW|Taiwan).*$",
    "(?i)^(?!.*(media)).*(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore).*$",
    "(?i)^(?!.*(media)).*(ğŸ‡ºğŸ‡¸|ç¾|US|United States).*$",
    "(?i)^(?!.*(media)).*(ğŸ‡¯ğŸ‡µ|[^-]æ—¥(?!ç”¨|åˆ©äºš)|JP|Japan).*$",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸ¼ EHGallery"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong)",
    "(ğŸ‡¹ğŸ‡¼|å°|TW|Taiwan)",
    "(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore)",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸµ TikTok"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸ¬ EMBY"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ“¹ YouTube"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
]

[[custom_groups]]
name = "ğŸ¥ Netflix"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
]

[[custom_groups]]
name = "ğŸ“º Bilibili"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "(æ¾³é—¨|MO|ğŸ‡²ğŸ‡´)",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rules = ["[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸµ Spotify"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ å›½å¤–æµé‡",
    "(è²å¾‹å®¾|PH)",
    "(å·´åŸºæ–¯å¦|PK)",
    "(åœŸè€³å…¶|TR|Turkey)",
    "(å°¼æ—¥åˆ©äºš|NG)",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
]

[[custom_groups]]
name = "ğŸ“² Telegram"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹",
]

[[custom_groups]]
name = "ğŸ’¬ OpenAi"
type = "select"
rules = [
    "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹",
    "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹",
    "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹",
    "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹",
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯äº‘ç›˜"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rules = ["[]ğŸš€ å›½å¤–æµé‡", "[]ğŸ¯ å›½å†…æµé‡", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rules = ["[]ğŸ¯ å›½å†…æµé‡", "[]ğŸš€ å›½å¤–æµé‡", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ“¢ è°·æ­ŒFCM"
type = "select"
rules = ["[]ğŸš€ å›½å¤–æµé‡", "[]ğŸ¯ å›½å†…æµé‡", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
type = "select"
rules = [
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸŒ å›½å†…åª’ä½“"
type = "select"
rules = ["[]ğŸ¯ å›½å†…æµé‡", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ•¹ï¸ æ¸¸æˆä¸‹è½½"
type = "select"
rules = [
    "[]ğŸ¯ å›½å†…æµé‡",
    "[]ğŸš€ å›½å¤–æµé‡",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1",
    "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2",
    "[]âœˆï¸ ä½å€ç‡èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ¯ å›½å†…æµé‡"
type = "select"
rules = ["[]DIRECT", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rules = ["[]REJECT", "[]DIRECT", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ›¡ï¸ éšç§é˜²æŠ¤"
type = "select"
rules = ["[]REJECT", "[]DIRECT", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©1", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©2"]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
type = "url-test"
rules = ["!!GROUPID=0!!(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "url-test"
rules = ["!!GROUPID=0!!(ğŸ‡­ğŸ‡°|æ¸¯|HK|Hong Kong)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹"
type = "url-test"
rules = ["!!GROUPID=0!!(ğŸ‡¹ğŸ‡¼|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "url-test"
rules = [
    "!!GROUPID=0!!(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥(?!ç”¨|åˆ©äºš)|JP|Japan)"
]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 50

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rules = [
    "!!GROUPID=0!!(ğŸ‡ºğŸ‡¸|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)",
]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
